igles:
    resource: "@IglesBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

igles_admin:
    resource: "@IglesBundle/Controller/AdminController.php"
    type: annotation

igles:
    resource: "@IglesBundle/Resources/config/routing.yml"

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

dcs_rating:
    resource: "@DCSRatingBundle/Resources/config/routing.xml"
    prefix:   /