<?php

namespace IglesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DefaultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefaultRepository extends EntityRepository
{

    public function getSerieLimit($nb=5)
    {
        $query = $this->_em->createQuery(
            'SELECT s
    		FROM IglesBundle:Series s
    		WHERE s.moderation = 0 
    		ORDER BY s.nomSerie DESC 
    		' )->setMaxResults($nb);

        return $query->getResult();

    }


}

