<?php

namespace IglesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EpisodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodesRepository extends EntityRepository
{
}
