<?php

namespace IglesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SaisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaisonRepository extends EntityRepository
{
	public function getEpisodes()
	{
		$query = $this->_em->createQuery(
    		'SELECT s, e
    		FROM IglesBundle:Saison s
    		INNER JOIN s.episodes e
    		WHERE e.moderationEpisode = 1
    		ORDER BY e.numeroEpisode ASC' );
		
		return $query->getResult();
		
	}

	public function getSaisons()
	{
		$query = $this->_em->createQuery(
    		'SELECT s, e, t
    		FROM IglesBundle:Saison s
    		INNER JOIN s.serie e
    		LEFT JOIN s.saisonPoster t
    		WHERE s.moderationSaison = 1
    		ORDER BY s.numeroSaisons ASC' );
		
		return $query->getResult();
		
	}

	public function getSeries($serieid){
		$query = $this->_em->createQyery(
			'SELECT s, e
			FROM IglesBundle:Series s
			INNER JOIN s.saison e
			WHERE s.id = :id'
		)->setParameter('id', $serieid);

		return $query->getResult();
	}

		public function getSaisonsModeration()
	{
		$query = $this->_em->createQuery(
    		'SELECT s, e
    		FROM IglesBundle:Saison s
    		INNER JOIN s.serie e
    		WHERE s.moderationSaison = 0
    		' );
		
		return $query->getResult();
		
	}

	public function countNotModererSaisons(){
		$query = $this->_em->createQuery(
			'SELECT s
			FROM IglesBundle:Saison s
			WHERE s.moderationSaison  = 0
			');
		
		return $query->getResult();
	}
}

