<?php

namespace IglesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SaisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaisonRepository extends EntityRepository
{
	public function getEpisodes()
	{
		$query = $em->createQuery(
    		'SELECT s, e
    		FROM IglesBundle:Saison s
    		INNER JOIN s.episode e');
		
		$saisons = $query->getResult();
		
		return $saisons;
	}
}
