<?php

namespace IglesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SeriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeriesRepository extends EntityRepository
{
	
	public function getSaisons()
	{
		$query = $em->createQuery(
    		'SELECT s, a
    		FROM IglesBundle:Series s
    		INNER JOIN s.saison a');
		
		$series = $query->getResult();
		
		return $series;
	}
}
