<?php

namespace IglesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SeriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeriesRepository extends EntityRepository
{
	public function getEpisodes()
	{
		$query = $em->createQuery(
    		'SELECT s
    		FROM IglesBundle:Series s
    		INNER JOIN s.episode e');
		
		$series = $query->getResult();
	}
}
