<?php

namespace IglesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{
	public function getUsers()
	{
		$query = $this->_em->createQuery(
    		'SELECT u, a
    		FROM IglesBundle:Users u
    		INNER JOIN u.avatar a
    		ORDER BY u.lastName ASC' );
		
		return $query->getResult();
		
	}
}
