igles_promote_user:
    path:    /promote/{id}
    defaults: { _controller: IglesBundle:Admin:promoteUser, id: 1 }
    requirements:
        id: /d+

igles_select_serie:
    path:    /series/{id}
    defaults: { _controller: IglesBundle:Series:select, id: 1 }

igles_select_episode:
    path:    /episode/{id}
    defaults: { _controller: IglesBundle:Episode:select, id: 1 }
    requirements:
        id: /d+

igles_saison:
    path:    /saison/
    defaults: { _controller: IglesBundle:Saison:index}

igles_delete_serie:
    path:    /delete/{id}
    defaults: { _controller: IglesBundle:Series:delete, id: 1 }

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

dcs_rating:
    resource: "@DCSRatingBundle/Resources/config/routing.xml"
    prefix:   /

igles_moderation:
    path:    /moderation
    defaults: { _controller: IglesBundle:Valide:index}
